Basic deployment approach in place

diff --git a/bin/jira-app b/bin/jira-app
--- a/bin/jira-app
+++ b/bin/jira-app
@@ -2,62 +2,79 @@
 set -eu
 set -o pipefail
 
-usage="Usage: $(basename $0) [-h]
+usage="Usage: $(basename $0) [-h][-r]
     -h - help
+    -r - restart
 
 Starts the jira-app in the background
 "
 
-options=""
+restart=0
 while [ $# -gt 0 ]; do
     case "$1" in
         -h|-\?)
             echo "$usage"
             exit 0
         ;;
+        -r)
+            restart=1
+        ;;
         *)
 	    break
-	;;
+        ;;
     esac
     shift
 done
 
 if [ -z "$AI_HOME" ]; then
-    echo "Error: AI_HOME not defined, have you setup the environment"
+    echo "Error: AI_HOME not defined, have you setup the environment" 1>&2
     exit 1
 fi
 
 if [ -z "$EXTOLE_SUPER_USER_API_KEY" ]; then
-    echo "Error: no enviornment variable EXTOLE_SUPER_USER_API_KEY"
+    echo "Error: no environment variable EXTOLE_SUPER_USER_API_KEY" 1>&2
     exit 1
 fi
 
 if ! command -v java &>/dev/null; then
-    echo "Error: java not found"
+    echo "Error: java not found" 1>&2
     exit 1
 fi
-
 
 app_home=$AI_HOME/jira-app
 
 mkdir -p $app_home/logs
 
-jar="$(find $app_home/libs -name "jira-app*.jar" | sort  | tail -1)" 
+jar="$(find $app_home/libs -name "jira-app*.jar" | sort | tail -1)"
 
-if pgrep -f libs/jira-app >/dev/null; then
-    if pgrep -f $jar >/dev/null; then
-        echo "jira-app already running on $(pgrep -f $jar)"
-        exit 0
-    else
-        echo "jira-app already running on $(pgrep -f libs/jira-app) is out of date"
-        exit 1
+if [ $restart -eq 1 ]; then
+    if pgrep -n -f $jar >/dev/null; then
+        echo -n "jira-app stopping..."
+        pkill -f $jar
+
+        end=$((SECONDS+240))
+        while pgrep -f $jar >/dev/null; do
+            if [ $SECONDS -ge $end ]; then
+                echo "failed."
+                echo "Failed to stop jira-app within 2 minutes." 1>&2
+                exit 1
+            fi
+            sleep 5
+            echo -n "."
+        done
+        echo "stopped."
     fi
 fi
 
-echo "Running: $jar"
+if pgrep -f libs/jira-app >/dev/null; then
+    echo "jira-app already running on $(pgrep -f libs/jira-app)"
+    exit 0
+fi
+
+echo "jira-app $jar last modified $(stat -c '%y' $jar)"
 
 cd $app_home
 nohup java -jar $jar >$app_home/logs/jira-app-output.log 2>&1 &
 
-echo "Running in background as process: $!"
+echo "jira-app running in background as process: $!"
 
