Extole managed tokens don't work across clients

diff --git a/bin/jira-app b/bin/jira-app
--- a/bin/jira-app
+++ b/bin/jira-app
@@ -2,8 +2,9 @@
 set -eu
 set -o pipefail
 
-usage="Usage: $(basename $0) [-h]
+usage="Usage: $(basename $0) [-h] token
     -h - help
+    token - extole super user token
 
 Starts the jira-app in the background
 "
@@ -16,7 +17,14 @@ while [ $# -gt 0 ]; do
             exit 0
         ;;
     esac
+    shift
 done
+
+if [ -z "$1" ]; then
+    echo "Error: no super user token specified"
+    exit 1
+fi
+export EXTOLE_SUPER_USER_TOKEN="$1"
 
 if [ -z "$AI_HOME" ]; then
     echo "Error: AI_HOME not defined, have you setup the environment"
