Extole super user key updated to support multiple clients

diff --git a/bin/jira-app b/bin/jira-app
--- a/bin/jira-app
+++ b/bin/jira-app
@@ -2,9 +2,8 @@
 set -eu
 set -o pipefail
 
-usage="Usage: $(basename $0) [-h] token
+usage="Usage: $(basename $0) [-h]
     -h - help
-    token - extole super user token
 
 Starts the jira-app in the background
 "
@@ -23,14 +22,13 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if [ ! -v 1 ]; then
-    echo "Error: no super user token specified"
-    exit 1
-fi
-export EXTOLE_SUPER_USER_API_KEY="$1"
-
 if [ -z "$AI_HOME" ]; then
     echo "Error: AI_HOME not defined, have you setup the environment"
+    exit 1
+fi
+
+if [ -z "$EXTOLE_SUPER_USER_API_KEY" ]; then
+    echo "Error: no enviornment variable EXTOLE_SUPER_USER_API_KEY"
     exit 1
 fi
 
